apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debezium.name" . }}-properties
  labels:
    {{- include "debezium.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.kafka.ssl_enabled }}
  truststore.jks: {{ .Values.kafka_ssl.truststore_jks }}
  {{- end }}
stringData:
  admin.properties: |
    security.protocol=SASL_SSL
    sasl.mechanism={{ .Values.kafka_ssl.sasl_mechanism }}
    ssl.truststore.location=/etc/kafka/truststore.jks
    ssl.truststore.password={{ .Values.kafka_ssl.truststore_password }}
    sasl.jaas.config={{ .Values.kafka_ssl.jaas_config }}
  connect-distributed.properties: |
    group.id={{ .Values.debezium.properties.group_id }}

    listeners=http://0.0.0.0:8083

    task.shutdown.graceful.timeout.ms=10000

    plugin.path=/kafka/connect

    key.converter=org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable=false
    value.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable=false
    internal.key.converter=org.apache.kafka.connect.json.JsonConverter
    internal.value.converter=org.apache.kafka.connect.json.JsonConverter

    offset.storage.topic={{ .Values.debezium.properties.topics_basename }}.offset
    offset.storage.replication.factor=1
    offset.flush.interval.ms=60000
    offset.flush.timeout.ms=5000

    config.storage.topic={{ .Values.debezium.properties.topics_basename }}.config
    config.storage.replication.factor=1

    status.storage.topic={{ .Values.debezium.properties.topics_basename }}.status
    status.storage.replication.factor=1

    bootstrap.servers={{ .Values.kafka.bootstrap_servers }}

    security.protocol=SASL_SSL
    sasl.mechanism={{ .Values.kafka_ssl.sasl_mechanism }}
    ssl.truststore.location=/etc/kafka/truststore.jks
    ssl.truststore.password={{ .Values.kafka_ssl.truststore_password }}
    sasl.jaas.config={{ .Values.kafka_ssl.jaas_config }}

    producer.security.protocol=SASL_SSL
    producer.sasl.mechanism={{ .Values.kafka_ssl.sasl_mechanism }}
    producer.ssl.truststore.location=/etc/kafka/truststore.jks
    producer.ssl.truststore.password={{ .Values.kafka_ssl.truststore_password }}
    producer.sasl.jaas.config={{ .Values.kafka_ssl.jaas_config }}

    producer.max.request.size={{ .Values.debezium.connect_properties.producer_max_request_size }}

    consumer.security.protocol=SASL_SSL
    consumer.sasl.mechanism={{ .Values.kafka_ssl.sasl_mechanism }}
    consumer.ssl.truststore.location=/etc/kafka/truststore.jks
    consumer.ssl.truststore.password={{ .Values.kafka_ssl.truststore_password }}
    consumer.sasl.jaas.config={{ .Values.kafka_ssl.jaas_config }}
